name: Continuous Integration

on:
  pull_request:
    branches:
      - ['main']

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  eslint:
    name: 'Eslint Pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn
      - name: Eslint check
        run: |
          echo "Checking Eslint"
          yarn run lint

  test:
    name: 'Tests Pipeline'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          yarn
      - name: Run tests
        run: |
          echo "Running tests"
          yarn run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
